# Netlify Configuration

# Student Frontend
[[redirects]]
  from = "/student"
  to = "/student-frontend/index.html"
  status = 200

# Admin Panel
[[redirects]]
  from = "/admin"
  to = "/admin-panel/index.html"
  status = 200

